### ISSUE TITLE
Validação Rondonia

### ISSUE THREAD

**Issue by vinidalmagro** [gammasoft/ie#6]
Olá,
Tive problemas em validar uma inscrição estadual para o estado de Rondonia
```
inscricaoEstadual("00000003836321","ro")
```

A lib me retornava false, sendo que esta inscrição foi retirada de um cadastro existente.
Depois ler o código, descobri que estava faltando a ultima parte da validação:
> No caso da diferença calculada no parágrafo anterior fornecer como resultado 10 ou 11, subtrai-se 10 da mesma para obter o dígito verificador.   

O resultado do calculo era igual a 121 que dividido por 11 resulta em 0.
Dessa forma, o digito tem que ser alterado para 1.

Segue código alterado:
```
ro: function(valor){
        var base, digito, resultadoMod;

        if(tamanhoE(valor, 9)) {
            base = valor.substring(3, 8);
            digito = substracaoPor11SeMaiorQue2CasoContrario0(mod(base));

            return valor === valor.substring(0, 3) + base + digito;
        } else if(tamanhoE(valor, 14)) {
            base = primeiros(valor, 13);
            resultadoMod = mod(base);
            digito = resultadoMod <= 1 ? 1 : 11 - resultadoMod
            // digito = substracaoPor11SeMaiorQue2CasoContrario0(mod(base));  MODO ANTIGO
            return valor === base + digito;
        } else {
            return false;
        }
    },
```

**Comment by renatoargh** [comment]
@vinidalmagro você consegue me passar mais inscrições estaduais de Rondônia? Atualmente nos testes só tem 3! Estou fazendo o merge e vou subir uma versão com a sua alteração.

**Comment by vinidalmagro** [comment]
Não tem como, issa informação veio através de uma solicitação de suporte
Em 05/10/2015 5:56 PM, "Renato Gama" <notifications@github.com> escreveu:

**Comment by renatoargh** [comment]
Ok, versão atualizada com a sua correção! `npm install inscricaoestadual@0.0.4`! Obrigado! Ps.: Da próxima vez manda um pull request para o seu nome aparecer como contribuidor do projeto. Abraço

**Comment by juarezfranco** [comment]
Olá passei por esse problema com estado de Rondônia.

Alterei o código com base na doc http://www.sintegra.gov.br/Cad_Estados/cad_RO.html  e  as minhas inscrições funcionaram
```js
       ...
       } else if(tamanhoE(valor, 14)) {
            base = primeiros(valor, 13);
            resultadoMod = 11 - mod(base);
            
            if (resultadoMod == 10 || resultadoMod == 11) {
                digito = resultadoMod - 10;
            } else {
                digito = resultadoMod;
            }

            return valor === base + digito;
        } else {
        ...

**Comment by renatoargh** [comment]
Galera, só relembrando que o projeto está descontinuado. Fora isso, muito
obrigado pela contribuição
