### ISSUE TITLE
Validação CE, DF, MT

### ISSUE THREAD

**Issue by felipetofoli** [gammasoft/ie#7]
Olá,

Primeiro, gostaria de parabenizar pelo trabalho. O código de validação me ajudou bastante!

No processo de implantação peguei alguns pontos:

- **CE**:
Na validação original constava uma restrição, que a IE do Ceará deveria começar com "06". Ao testar a IE de alguns clientes, percebemos que a regra não era válida e não está de acordo com a especificação no [Sintegra](http://www.sintegra.gov.br/Cad_Estados/cad_CE.html).

Código alterado:
ce: function(valor){
        if(tamanhoNaoE(valor)) {
            return false;
        }

        return calculoTrivial(valor);
    },

- **DF**:
Na especificação do [Sintegra](http://www.sintegra.gov.br/Cad_Estados/cad_DF.html) cita que o IE do Distrito Federal sempre deve começar com "07". Adicionei a validação:
df: function(valor){
        if(tamanhoNaoE(valor, 13)) {
            return false;
        }
		
	if(naoComecaCom(valor, '07')) {
            return false;
        }

        var base = primeiros(valor, 11);

        var primeiro = substracaoPor11SeMaiorQue2CasoContrario0(mod(base));
        var segundo = substracaoPor11SeMaiorQue2CasoContrario0(mod(base + primeiro));

        return valor === base + primeiro + segundo;
    }

- **MT**:
A validação estava quebrando pela falta de um parâmetro na chamada do método de calculo trivial:
mt: function(valor){
        if(tamanhoNaoE(valor, 11) && tamanhoNaoE(valor)) {
            return false;
        }

        var base = tamanhoE(valor, 11) ? valor.substring(0, 10) : primeiros(valor);
        return calculoTrivial(valor, base, true);
    },

**Comment by renatoargh** [comment]
Olá @felipetofoli muito obrigado pela sua contribuição. Por acaso você teria algum pull request com as modificações ou está apenas apontando os bugs? De qualquer maneira você poderia enviar para o meu email algumas IE que falham para que eu possa corrigir e testar? Meu email é renatoargh@gmail.com - Muitissimo obrigado! Abraço

**Comment by felipetofoli** [comment]
Olá @renatoargh , 

Gostaria muito de poder contribuir, mas estou com uma restrição de infra e não consigo clonar o repositório no momento...

Mandei, no seu email, o arquivo js com as correções e a massa utilizada para testes.

Obrigado pela atenção.

Abraço!

**Comment by renatoargh** [comment]
Fala, @felipetofoli valeu! Vou fazer o merge, atualizar os testes e colocar seu nome como contribuidor mas só terei tempo no fim de semana. Assim que fizer atualizo no npm e te aviso! PS.: Até o momento não recebi o email. Abraço!

**Comment by felipetofoli** [comment]
Oi @renatoargh ,

Enviei novamente o email, caso ainda não tivesse recebido. Qualquer coisa, só avisar.

Abraço!

**Comment by renatoargh** [comment]
Felipe, acho que tem algo errado, ja procurei aqui na caixa de entrada e não encontro de jeito nenhum, tem como mandar em um gist? :/

**Comment by renatoargh** [comment]
Fechado por inatividade

**Comment by maikonformigari** [comment]
Olá,

realmente existem esses bugs apontados pelo @felipetofoli.

@renatoargh você poderia verificar o pull request enviado pelo @felipetofoli e realizar o merge?

Obrigado e parabéns pela biblioteca.
